### PR TITLE
OSX-arm64 support

### PR DESCRIPTION
**Pull request by ChristopherMayes**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hhslepicka** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
@isuruf Thank you for the help! This package uses a custom build system based on a bunch of scripts and CMake. We are also getting an error related to the architecture not being supported when trying to build the test Fortran program before compiling the package code, which I imagined could be related to the `gnuconfig`, but I could not figure out why.

**Comment by isuruf** [comment]
You need to patch `cmake` call to `cmake ${CMAKE_ARGS}` in `util/mk-mkd`.

**Comment by ChristopherMayes** [comment]
@isuruf thanks, we applied a patch for the call to `cmake`. But it is still failing on:
 ```
f951: Error: bad value 'armv8.3-a' or '-march=' switch
```

**Comment by ChristopherMayes** [comment]
@conda-forge-admin, please rerender

**Comment by hhslepicka** [comment]
Depends on Xraylib Fortran bindings being enabled.
Working on that here https://github.com/conda-forge/xraylib-feedstock/pull/45

**Comment by ChristopherMayes** [comment]
@isuruf it now seems to be stuck on the final `conda-build` step. Could you help with that?

**Comment by ChristopherMayes** [comment]
@isuruf it worked! Thank you for your help! I'm doing some cleanup now.

**Comment by hhslepicka** [comment]
celebrate

**Pull request merged**
